include:
  - docker-compose.stack.yml

services:
  zoomeet:
    image: anatoliydev7/zoomeet:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - PUBLIC_LIVEKIT_URL=${PUBLIC_LIVEKIT_URL}
    depends_on:
      - livekit
    networks:
      - default
      - dokploy-network
